name: Release
run-name: Releasing
on: [release]
jobs:
  linux_files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build & test
        run: |
          cmake -H. -B_build
          cmake --build _build
      - name: packages
        run: |
          cd _build
          cpack -G "DEB"
          cpack -G "RPM"
          cpack -G "TGZ"
          cd ..
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: arts1
          path: _build/bank_lib-*
  windows_files:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -S D:/a/LR_6/LR_6 -B D:/a/LR_6/LR_6/_build
          cmake --build _build
      - name: Make art
        run: |
          cd _build
          cpack -G "ZIP"
          cpack -G "NSIS"
          cd ..
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: arts2
          path: _build/bank_lib-*
