name: Test
run-name: Testing
on: [push]
jobs:
  test:
    if: ${{ !startsWith( github.event.ref , '/refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build & test
        run: |
          cmake -H. -B_build -DTEST=ON
          cmake --build _build
          cmake --build _build --target test -- ARGS=--verbose
      - name: Report to Coveralls
        uses: threeal/gcovr-action@v1.0.0
        with:
          excludes: third-party
          coveralls-send: true
          github-token: ${{ secrets.GITHUB_TOKEN }}


